authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: ou=People,dc=northwestern,dc=edu

defaults: &DEFAULTS
  host: registry.northwestern.edu
  port: 636
  attribute: uid
  base: dc=northwestern,dc=edu
  admin_user: cn=fsm-lurie-plutus, ou=pwcheck, dc=northwestern, dc=edu
  admin_password: <%= ENV['LDAP_PASSWORD'] %>
  ssl: true

development:
  <<: *DEFAULTS
  host: ldap
  port: 389
  attribute: nuIdTag
  ssl: false
  admin_user: cn=admin,dc=northwestern,dc=edu
  admin_password: password
  <<: *AUTHORIZATIONS

production:
  <<: *AUTHORIZATIONS
  <<: *DEFAULTS

staging:
  <<: *AUTHORIZATIONS
  <<: *DEFAULTS
